{
 "title": "Capacity Management",
 "tags": [ "RedHat COP" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "nodegroup",
    "label": "Node Group",
    "query": "label_values(kube_node_labels,label_nodegroup)"
   }
  ]
 },
 "panels": [
  {
   "title": "$nodegroup Node Group Memory Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Quota / Allocatable in Node Group: $nodegroup",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "quota_sum:memory:by_nodegroup{label_nodegroup=\"$nodegroup\"}/allocatable_sum:memory:by_nodegroup{label_nodegroup=\"$nodegroup\"}"
    }
   ]
  },
  {
   "title": "Pod requests / Allocatable in Node Group: $nodegroup",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "request_sum:memory:by_nodegroup{label_nodegroup=\"$nodegroup\"}/allocatable_sum:memory:by_nodegroup{label_nodegroup=\"$nodegroup\"}"
    }
   ]
  },
  {
   "title": "Current Memory Usage / Allocatable in Node Group: $nodegroup",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "usage_sum:memory:by_nodegroup{label_nodegroup=\"$nodegroup\"}/allocatable_sum:memory:by_nodegroup{label_nodegroup=\"$nodegroup\"}"
    }
   ]
  },
  {
   "title": "Sum of Quotas",
   "type": "singlestat",
   "description": "What has been promised",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "quota_sum:memory:by_nodegroup{label_nodegroup=\"$nodegroup\"}"
    }
   ]
  },
  {
   "title": "Sum of Pod Requests",
   "type": "singlestat",
   "description": "What developers estimate they will need",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "request_sum:memory:by_nodegroup{label_nodegroup=\"$nodegroup\"}"
    }
   ]
  },
  {
   "title": "Current Memory Utilization",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "usage_sum:memory:by_nodegroup{label_nodegroup=\"$nodegroup\"}"
    }
   ]
  },
  {
   "title": "$nodegroup Node Group CPU Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "Quota/ Allocatable in Node Group: $nodegroup",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "quota_sum:cpu:by_nodegroup{label_nodegroup=\"$nodegroup\"}/allocatable_sum:cpu:by_nodegroup{label_nodegroup=\"$nodegroup\"}"
    }
   ]
  },
  {
   "title": "Pod requests / Allocatable in Node Group: $nodegroup",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "request_sum:cpu:by_nodegroup{label_nodegroup=\"$nodegroup\"}/allocatable_sum:cpu:by_nodegroup{label_nodegroup=\"$nodegroup\"}"
    }
   ]
  },
  {
   "title": "Current CPU Usage in Node Group: $nodegroup",
   "type": "singlestat",
   "description": "OS and Container CPU usage",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "usage_sum:cpu:by_nodegroup{label_nodegroup=\"$nodegroup\"} / allocatable_sum:cpu:by_nodegroup{label_nodegroup=\"$nodegroup\"}"
    }
   ]
  },
  {
   "title": "Sum of Quotas",
   "type": "singlestat",
   "description": "What has been promised",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "quota_sum:cpu:by_nodegroup{label_nodegroup=\"$nodegroup\"}"
    }
   ]
  },
  {
   "title": "Sum of Pod Requests",
   "type": "singlestat",
   "description": "What developers estimate they will need",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "request_sum:cpu:by_nodegroup{label_nodegroup=\"$nodegroup\"}"
    }
   ]
  },
  {
   "title": "Current CPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "usage_sum:cpu:by_nodegroup{label_nodegroup=\"$nodegroup\"} "
    }
   ]
  }
 ]
}